<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Doc_model extends CI_Model{
	function batch_save_child($arr){
		$this->db->insert_batch('pos_doc_child', $arr); 
	}
	function save_main($arr){
		$this->db->insert('pos_doc',$arr);
		return $this->db->insert_id();
	}
	function getNextInv($branch){
		$this->load->model('branch_model');
		$branch_info = $this->branch_model->getByID($branchID);
	}
	function getDocByID($id){
		$this->db->where('pos_doc_id',$id);

		$query = $this->db->get('pos_doc');

		return $query->row();
	}
   
}

/* End of file Members_model.php */
/* Location: ./application/models/Members_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-11-22 20:47:24 */
/* http://harviacode.com */