<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Members_model extends CI_Model
{

    public $table = 'mod_clients';
    public $id = 'mod_clients_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('mod_clients_id', $q);
	$this->db->or_like('mod_clients_fullname', $q);
	$this->db->or_like('mod_clients_fullname_zh', $q);
	$this->db->or_like('mod_clients_nric', $q);
	$this->db->or_like('mod_clients_email', $q);
	$this->db->or_like('mod_clients_occupation', $q);
	$this->db->or_like('mod_clients_marital_status', $q);
	$this->db->or_like('mod_clients_gender', $q);
	$this->db->or_like('mod_clients_nationality', $q);
	$this->db->or_like('mod_clients_birthday', $q);
	$this->db->or_like('mod_clients_contact_1', $q);
	$this->db->or_like('mod_clients_contact_2', $q);
	$this->db->or_like('mod_clients_attr_1', $q);
	$this->db->or_like('mod_clients_attr_2', $q);
	$this->db->or_like('mod_clients_address', $q);
	$this->db->or_like('mod_clients_address_country', $q);
	$this->db->or_like('mod_clients_address_state', $q);
	$this->db->or_like('col_05', $q);
	$this->db->or_like('col_17', $q);
	$this->db->or_like('col_21', $q);
	$this->db->or_like('col_24', $q);
	$this->db->or_like('col_25', $q);
	$this->db->or_like('mod_clients_passport', $q);
	$this->db->or_like('mod_clients_place_of_birth', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('mod_clients_id', $q);
	$this->db->or_like('mod_clients_fullname', $q);
	$this->db->or_like('mod_clients_fullname_zh', $q);
	$this->db->or_like('mod_clients_nric', $q);
	$this->db->or_like('mod_clients_email', $q);
	$this->db->or_like('mod_clients_occupation', $q);
	$this->db->or_like('mod_clients_marital_status', $q);
	$this->db->or_like('mod_clients_gender', $q);
	$this->db->or_like('mod_clients_nationality', $q);
	$this->db->or_like('mod_clients_birthday', $q);
	$this->db->or_like('mod_clients_contact_1', $q);
	$this->db->or_like('mod_clients_contact_2', $q);
	$this->db->or_like('mod_clients_attr_1', $q);
	$this->db->or_like('mod_clients_attr_2', $q);
	$this->db->or_like('mod_clients_address', $q);
	$this->db->or_like('mod_clients_address_country', $q);
	$this->db->or_like('mod_clients_address_state', $q);
	$this->db->or_like('col_05', $q);
	$this->db->or_like('col_17', $q);
	$this->db->or_like('col_21', $q);
	$this->db->or_like('col_24', $q);
	$this->db->or_like('col_25', $q);
	$this->db->or_like('mod_clients_passport', $q);
	$this->db->or_like('mod_clients_place_of_birth', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data){
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data){
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id){
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
    function checkExistedIC($nric){
		$this->db->where('mod_clients_nric',$nric);
		$this->db->or_where('mod_clients_nric',str_replace('-', '', $nric));
		$query = $this->db->get('mod_clients');

		return $query->row(); 
	}

}

/* End of file Members_model.php */
/* Location: ./application/models/Members_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-11-22 20:47:24 */
/* http://harviacode.com */