<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Payment_model extends CI_Model{
	function batch_save($arr){
		$this->db->insert_batch('pos_payment', $arr); 
	}
   
}

/* End of file Members_model.php */
/* Location: ./application/models/Members_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-11-22 20:47:24 */
/* http://harviacode.com */