<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Products_model extends CI_Model
{

    public $table = 'ds_product';
    public $id = 'ds_product_id';
    public $order = 'DESC';

    function __construct(){
        parent::__construct();
    }

    // get all
    function get_all(){
        //$this->db->join('ds_product_category', 'ds_product_category.ds_product = ds_product.ds_product_id','left');
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }
    function get_all_is_service(){
        $this->db->where('ds_product_is_service','1');
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }
    function get_all_non_service(){
        //$this->output->enable_profiler(TRUE);
        $this->db->where('ds_product_is_service IS NULL');
        $this->db->or_where('ds_product_is_service','');
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id){
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->join('ds_product_category', 'ds_product_category.ds_product_category_id = ds_product.ds_product_category','left');
    	$this->db->like('ds_product_name', $q);
        $this->db->or_like('ds_product_category.ds_product_category_name', $q);
    	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->join('ds_product_category', 'ds_product_category.ds_product_category_id = ds_product.ds_product_category','left');
    	$this->db->like('ds_product_name', $q);
        $this->db->or_like('ds_product_category.ds_product_category_name', $q);
        $this->db->order_by($this->id, $this->order);
    	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id){
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
    function get_by_category($id){
        $this->db->where('ds_product_category',$id);
        return $this->db->get($this->table)->row();
    }

}

/* End of file Products_model.php */
/* Location: ./application/models/Products_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-11-23 14:40:40 */
/* http://harviacode.com */