<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Product_attribute_sub_model extends CI_Model
{

    public $table = 'ds_product_attribute_sub';
    public $id = 'ds_product_attribute_sub_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }
    function get_by_main_id($main_id){

        $this->db->where('ds_product_attribute_parent_id', $main_id);
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }
    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('ds_product_attribute_sub_id', $q);
	$this->db->or_like('ds_product_attribute_parent_id', $q);
	$this->db->or_like('ds_product_attribute_sub_name', $q);
	$this->db->or_like('ds_product_attribute_sub_enable', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('ds_product_attribute_sub_id', $q);
    	$this->db->or_like('ds_product_attribute_parent_id', $q);
    	$this->db->or_like('ds_product_attribute_sub_name', $q);
    	$this->db->or_like('ds_product_attribute_sub_enable', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
    function has_sub_batch_insert($data){
        $this->db->insert_batch('ds_product_has_attribute', $data); 
    }

}

/* End of file Product_attribute_sub_model.php */
/* Location: ./application/models/Product_attribute_sub_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-12-01 19:56:27 */
/* http://harviacode.com */